### ISSUE TITLE
hasMany and belongsToMany 

### ISSUE THREAD

**Issue by LubosRemplik** [riesenia/persist-related-data#5]
This works with `belongsTo` very well but sometimes you need to save data from `hasMany` or `belongsToMany` associations. We can use separator to join data into one field (something like `implode($separator = PHP_EOL, Hash::extract($contact->numbers, '{n}.number'))` if you see what I mean.

What you think? Worth to make PR?

**Comment by segy** [comment]
sure. this feature is welcome
